import fs from "fs";
import path from "path";

interface SlackBlock {
  type: string;
  text?: { type: string; text: string; emoji?: boolean };
  elements?: Array<Record<string, unknown>>;
  image_url?: string;
  alt_text?: string;
  block_id?: string;
  accessory?: Record<string, unknown>;
  fields?: Array<{ type: string; text: string }>;
}

// ── Send a simple message via webhook ──
export async function sendSlackWebhook(
  text: string,
  blocks?: SlackBlock[]
): Promise<void> {
  const webhookUrl = process.env.SLACK_WEBHOOK_URL;
  if (!webhookUrl) throw new Error("SLACK_WEBHOOK_URL not configured");

  const res = await fetch(webhookUrl, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ text, blocks }),
  });

  if (!res.ok) {
    throw new Error(`Slack webhook error (${res.status}): ${await res.text()}`);
  }
}

// ── Send a rich message with bot token (for interactive buttons) ──
export async function sendSlackMessage(
  channel: string,
  text: string,
  blocks?: SlackBlock[]
): Promise<{ ts: string; channel: string }> {
  const token = process.env.SLACK_BOT_TOKEN;
  if (!token) throw new Error("SLACK_BOT_TOKEN not configured");

  const res = await fetch("https://slack.com/api/chat.postMessage", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ channel, text, blocks }),
  });

  const data = await res.json();
  if (!data.ok) {
    throw new Error(`Slack API error: ${data.error}`);
  }

  return { ts: data.ts, channel: data.channel };
}

// ── Upload an image to Slack ──
export async function uploadSlackImage(
  channel: string,
  filePath: string,
  title: string
): Promise<void> {
  const token = process.env.SLACK_BOT_TOKEN;
  if (!token) throw new Error("SLACK_BOT_TOKEN not configured");

  const resolvedPath = path.resolve(filePath);
  if (!fs.existsSync(resolvedPath)) {
    throw new Error(`File not found: ${resolvedPath}`);
  }

  const fileBuffer = fs.readFileSync(resolvedPath);
  const formData = new FormData();
  formData.append("file", new Blob([fileBuffer]), path.basename(filePath));
  formData.append("channels", channel);
  formData.append("title", title);
  formData.append("initial_comment", `Generated image: ${title}`);

  const res = await fetch("https://slack.com/api/files.upload", {
    method: "POST",
    headers: { Authorization: `Bearer ${token}` },
    body: formData,
  });

  const data = await res.json();
  if (!data.ok) {
    throw new Error(`Slack upload error: ${data.error}`);
  }
}

// ── Post approved image to Slack ──
export async function postApprovedImage(
  jobId: number,
  outputPath: string,
  prompt: string,
  characterName: string
): Promise<void> {
  const webhookUrl = process.env.SLACK_WEBHOOK_URL;
  const botToken = process.env.SLACK_BOT_TOKEN;

  if (botToken) {
    // Use bot token for richer messages
    const channel = process.env.SLACK_CHANNEL || "#content";
    await sendSlackMessage(channel, `Approved image from ${characterName}`, [
      {
        type: "header",
        text: { type: "plain_text", text: `Approved: ${characterName}`, emoji: true },
      },
      {
        type: "section",
        fields: [
          { type: "mrkdwn", text: `*Job:* #${jobId}` },
          { type: "mrkdwn", text: `*Character:* ${characterName}` },
        ],
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: `*Prompt:*\n>${prompt.slice(0, 200)}${prompt.length > 200 ? "..." : ""}`,
        },
      },
      {
        type: "context",
        elements: [
          { type: "mrkdwn", text: `Generated by Mecha AI | ${new Date().toLocaleString()}` },
        ],
      },
    ]);

    // Also upload the actual image file
    await uploadSlackImage(channel, outputPath, `Job #${jobId} - ${characterName}`);
  } else if (webhookUrl) {
    // Fallback to webhook (no file upload)
    await sendSlackWebhook(`Approved image from ${characterName} (Job #${jobId})`, [
      {
        type: "header",
        text: { type: "plain_text", text: `Approved: ${characterName}`, emoji: true },
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: `*Prompt:*\n>${prompt.slice(0, 200)}`,
        },
      },
    ]);
  }
}

// ── Post video plan for approval (with interactive buttons) ──
export async function postVideoApprovalRequest(
  jobId: number,
  characterName: string,
  prompt: string,
  videoType: "talking_head" | "motion_capture"
): Promise<{ ts: string; channel: string }> {
  const token = process.env.SLACK_BOT_TOKEN;
  if (!token) throw new Error("SLACK_BOT_TOKEN required for interactive approval");

  const channel = process.env.SLACK_CHANNEL || "#content";
  const typeLabel = videoType === "talking_head" ? "Talking Head" : "Motion Capture";

  return sendSlackMessage(
    channel,
    `${typeLabel} video approval request for ${characterName}`,
    [
      {
        type: "header",
        text: {
          type: "plain_text",
          text: `${typeLabel} Video — Approval Required`,
          emoji: true,
        },
      },
      {
        type: "section",
        fields: [
          { type: "mrkdwn", text: `*Character:* ${characterName}` },
          { type: "mrkdwn", text: `*Job:* #${jobId}` },
          { type: "mrkdwn", text: `*Type:* ${typeLabel}` },
        ],
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: `*Planned Prompt:*\n>${prompt.slice(0, 300)}`,
        },
      },
      {
        type: "actions",
        block_id: `video_approval_${jobId}`,
        elements: [
          {
            type: "button",
            text: { type: "plain_text", text: "Approve", emoji: true },
            style: "primary",
            action_id: "approve_video",
            value: String(jobId),
          },
          {
            type: "button",
            text: { type: "plain_text", text: "Reject", emoji: true },
            style: "danger",
            action_id: "reject_video",
            value: String(jobId),
          },
        ],
      },
    ]
  );
}
